# Generated by Django 3.2.23 on 2023-12-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20231128_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estadoPrestamo',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado')], max_length=20),
        ),
    ]
