# Generated by Django 3.2.23 on 2023-12-12 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20231212_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estadoPrestamo',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaDevolucion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuarioPrestado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
